### ISSUE TITLE
How to bind to E.164 number?

### ISSUE THREAD

**Issue by jacobg** [LouisMazel/vue-phone-number-input#1]
First of all, nice component!

This component is a composition of country code and local number. But it seems that the v-model is just the formatted local number. How do I bind the whole thing? Ideally, it would be able to bind to the E.164 phone number, which is the formattedNumber field in the object emitted by onUpdate event.

**Comment by jacobg** [comment]
I had to write a wrapper around the component to achieve the functionality I need, but it seems that vue-phone-number-input needs to formalize canonical bindings:

```
<template>
  <vue-phone-number-input
    ref="widget"
    v-bind="$attrs"
    v-on="forwardListeners"
    v-model="forwardValue"
    @update="onUpdate"
  />
</template>
<script>
import VuePhoneNumberInput from 'vue-phone-number-input'
import { parsePhoneNumberFromString, AsYouType } from 'libphonenumber-js'

export default {
  name: 'E164PhoneNumberInput',
  inheritAttrs: false,
  components: {
    VuePhoneNumberInput
  },
  props: ['value'],
  computed: {
    forwardListeners () {
      const { input, ...listeners } = this.$listeners
      return listeners
    },
    forwardValue: {
      get () {
        if (!this.value) return
        const asYouType = new AsYouType(this.$refs.widget.countryCode)
        const phoneNumber = parsePhoneNumberFromString(this.value)
        return phoneNumber && asYouType.input(phoneNumber.formatNational())
      },
      set (v) {
        if (!this.$refs.widget) return
        const phoneNumber = parsePhoneNumberFromString(v, this.$refs.widget.countryCode)
        const value = phoneNumber && phoneNumber.format('E.164')
        if (value !== this.value) this.$emit('input', value)
      }
    }
  },
  watch: {
    value (value) {
      if (!value) return
      const phoneNumber = parsePhoneNumberFromString(value)
      if (phoneNumber.country && phoneNumber.country !== this.$refs.widget.countryCode) {
        this.$refs.widget.countryCode = phoneNumber.country
      }
    }
  },
  methods: {
    // onUpdate handles case where country code was changed,
    // since v-model doesn't capture country code.
    onUpdate (data) {
      if (!this.value) return
      const phoneNumber = this.value && parsePhoneNumberFromString(this.value)
      if (!phoneNumber || data.formattedNumber !== phoneNumber.format('E.164')) {
        this.$emit('input', data.formattedNumber)
      }
    }
  }
}
</script>
<style lang="scss" scoped>
.vue-phone-number-input {
  // Small screens can't fit entire component on one line,
  // so split it into two.
  @include media-breakpoint-down(xs) {
    flex-direction: column;

    /deep/ .select-country-container {
      flex: 0 0 45px;
    }
  }
}
</style>
<style lang="css">
@import '~vue-phone-number-input/dist/vue-phone-number-input.css';
</style>
```

**Comment by LouisMazel** [comment]
I will add the E.164 format in next release 
PR : #7

**Comment by jacobg** [comment]
Thanks. I looked at your commit. That includes the E.164 in the object emitted by updateValues. But it doesn't bind the component to a an E.164 prop value, neither 1-way nor 2-way binding. I guess I don't understand why the value prop (v-model) doesn't use an E.164 value? That is the canonical value of the component. Why would there be an input for a country code, but the value prop doesn't include it? How is a saved phone number supposed to be loaded into a form?

**Comment by MLDMoritz** [comment]
While this is closed, I support @jacobg . v-model should be with country code. Only giving this out via @update makes this unnecessarily complex.

**Comment by LouisMazel** [comment]
Hi, 

The feature/correction about `e164` is now available on the new version of this component ! 
The new version of VuePhoneNumberInput is now on my **new library** [Maz-UI](https://louismazel.github.io/maz-ui/)

See **doc/demo** page of [MazPhoneNumberInput](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input)
Some options may change, check the props documentation with the top right button

In this new library, you can enjoy lot of others components in the same style. 
You can just install the component you want (and not the whole library), for this
Read the [Get started](https://louismazel.github.io/maz-ui/#/documentation/get-started) page

If you have any problem or question, do no hesitate to ask me !
