### ISSUE TITLE
[Bug] When country code has 3 numbers it doesn't recognize on prefill

### ISSUE THREAD

**Issue by MagdielCAS** [LouisMazel/vue-phone-number-input#10]
Like portugal (+351), when the prefilled number (+351345912678) has the country code of portugal the input doesn't recognize the correct code

in the example bellow the number +351345912678 was prefilled in the phone-number-input's v-model when page loaded
![image](https://user-images.githubusercontent.com/7864626/54435916-573a5400-4710-11e9-938f-445e6b9b5270.png)

**Comment by LouisMazel** [comment]
Hi, 

The component does not recognize automatically the country code. You (or the user) should set the country code with `default-country-code` attribute

**Comment by sombatos** [comment]
@MagdielCAS Have you found a way to set the country?
