### ISSUE TITLE
Open the countries layer above the input

### ISSUE THREAD

**Issue by IsraelDominguez** [LouisMazel/vue-phone-number-input#100]
If the phone input is at the bottom of a page and we do not have the possibility to scroll, the layer with the countries is not seen correctly. Possibility of show the countries layer open above the input.

**Comment by IsraelDominguez** [comment]
I have solve with property with a different class for load country-selector__list

.country-selector__list {
        top: -215px !important;
}

**Comment by LouisMazel** [comment]
Hi, 

The bug it's already fixed on the new version of this component ! 
The new version of VuePhoneNumberInput is now on my **new library** [Maz-UI](https://louismazel.github.io/maz-ui/)

See **doc/demo** page of [MazPhoneNumberInput](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input)
Some options may change, check the props documentation with the top right button

In this new library, you can enjoy lot of others components in the same style. 
You can just install the component you want (and not the whole library), for this
Read the [Get started](https://louismazel.github.io/maz-ui/#/documentation/get-started) page

If you have any problem or question, do no hesitate to ask me !
