### ISSUE TITLE
What is the point of having area code? if the area code is not added to the v-modal?

### ISSUE THREAD

**Issue by cjlaborde** [LouisMazel/vue-phone-number-input#102]
What is the point of having area code? if the area code can't be added.
Make the value add the area code in front like this for example for area code +1 make v-model value 189056756
As well don't add the  + symbol or spaces of ( 
It makes it not work with nexmo.

https://github.com/EducationLink/vue-tel-input 
works out of the box but their style is not at nice as this one.

Need to make it work for Nexmo and other services.
https://www.nexmo.com/blog/2018/08/21/phone-call-web-browser-nexmo-in-app-voice-vue-js-dr

**Comment by mberkeland** [comment]
I use it with Nexmo quite a bit. I probably have at least 15 projects using this control with Nexmo. I'm not really clear what the issue is that you are experiencing. I do agree having an e164 input mode would be really useful, though, and I believe there is a current open request for that

**Comment by LouisMazel** [comment]
Hi, 

The feature/correction about `e164` is now available on the new version of this component ! 
The new version of VuePhoneNumberInput is now on my **new library** [Maz-UI](https://louismazel.github.io/maz-ui/)

See **doc/demo** page of [MazPhoneNumberInput](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input)
Some options may change, check the props documentation with the top right button

In this new library, you can enjoy lot of others components in the same style. 
You can just install the component you want (and not the whole library), for this
Read the [Get started](https://louismazel.github.io/maz-ui/#/documentation/get-started) page

If you have any problem or question, do no hesitate to ask me !

**Comment by cjlaborde** [comment]
> I use it with Nexmo quite a bit. I probably have at least 15 projects using this control with Nexmo. I'm not really clear what the issue is that you are experiencing. I do agree having an e164 input mode would be really useful, though, and I believe there is a current open request for that

Greetings mberkeland

I tried again and got the phone number like this.

```js
       getPhoneNumber(data) {
                this.formattedNumber = data.formattedNumber.substr(1);
            },
```
removing the  + at the beginning is that the way you get the phone value as well?

**Comment by mberkeland** [comment]
Hello!
I set the @update="onUpdate1"
and in the update function I put this snippet:
onUpdate1(payload) {
if (payload.isValid) {
this.number1 = payload.formattedNumber.replace(/\D/g, '');

and "number1" is what can be fed to Nexmo.  Hope that helps!!
