### ISSUE TITLE
Number isn't formatted when value is gotten from Vuex store

### ISSUE THREAD

**Issue by alexsonnay** [LouisMazel/vue-phone-number-input#104]
## Describe the bug

Great plugin ! My issue :

When value is gotten from Vuex store, the number displayed in the input is : 0601020304 ❌
When input is focus and then blurred : 06 01 02 03 04 👍

Any idea how to get the value formatted when value is gotten from Vuex store once the component is mounted ?

**Comment by LouisMazel** [comment]
Hi @alexsonnay,

It's fixed on my new library [MazUi](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input) ?

Thanks for your feedback

- [Discover the new library here](https://louismazel.github.io/maz-ui/)
- [MazUi's Github](https://github.com/LouisMazel/maz-ui)
