### ISSUE TITLE
[Feature Request] Country code not updated when phone number is being changed from API

### ISSUE THREAD

**Issue by lilian21** [LouisMazel/vue-phone-number-input#105]
## Describe the bug

When updating v-model attribute with API data, country code not updating according to phone number coming from API but its being fetched from browser. 

## Steps to reproduce

1. `<vue-phone-number-input v-model="company_phone_number" no-example 
 @update="onCompanyPhoneUpdate"/>`
2.    `self.company_phone_number = response.data.company_phone_number; 
_response.data.company_phone_number is '+33612345678'_

3. Country code is not showing 'FR' as expected, it is still 'RO', as fetched from browser locale. Also it is formatting the '+33612345678' to `phoneNumber:"612345678"` which is ok if the country code updates correctly.

## Device (please complete the following information)

- OS: Windows 10
- Browser: Chrome 83
- Package version: 1.1.19

**Comment by LouisMazel** [comment]
Hi, 

It's not a bug, this feature is not available for now. You have to put yourself the country code. 

I will add this feature in the next version of this plugin on my new library

- [The page of the component on my new library](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input)
- [Your issue/feature request in the new library](https://github.com/LouisMazel/maz-ui/issues/39)
- [Discover the new library here](https://louismazel.github.io/maz-ui/)
- [Github](https://github.com/LouisMazel/maz-ui)

**Comment by LouisMazel** [comment]
Hi @lilian21,

Now you can enjoy the auto-detection of country from the phone number provided in the last version of [Maz-UI (1.2.2)](https://louismazel.github.io/maz-ui/)

**MazPhoneNumberInput**: [Documentation & Demo](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input)
**MAZ-UI - RELEASE 1.2.2 - Changelog**: https://github.com/LouisMazel/maz-ui/releases/tag/v1.2.2

**Comment by lilian21** [comment]
Thank you very much, @LouisMazel , keep up the good work !!

**Comment by lilian21** [comment]
Hi @LouisMazel,
I just tested the new library and features and I have a problem by setting phone number to a VueJS variable. 
`<maz-phone-number-input v-model="phone_number" />`
```
data: {
phone_number: null
}
mounted: function() {
  this.getUserProfileSettings();
}
methods: {
getUserProfileSettings: function () { 
   this.phone_number = "+336123456789"; // if I set it here it works perfect, it sets automatically country code.
   axios.get(URL).then(response => {
   if(response.data.type == 'success') {
     this.phone_number = response.data.phone_number; // setting it here doesn't work at all, it doesnt change anything in input,
   } 
  }
 }
}
```
As per code above, changing this.phone_number inside axios request doesn't work at all, even if I hardcode it: `this.phone_number = "+33612555555";` 
Below is a snapshot of MazPhoneNumberInput component from Vue DevTools. As you can see, it sets the value property right but anything else is wrong.
```
color:"primary"
countriesHeight:30
dark:false
defaultCountryCode:null
disabled:false
fetchCountry:false
id:null
ignoredCountries:Array[0]
noCountrySelector:false
noExample:false
noFlags:false
noUseBrowserLocale:false
noValidation:false
onlyCountries:null
preferredCountries:null
showCodeOnList:false
size:null
translations:null
value:"+33612555555"
inputValueFormatted:null
lastKeyPressed:null
results:Object (empty)
uniqueId:"MazPhoneNumberInput-12"
userLocale:"RO"
callingCode:"+40"
codesCountries:Array[242]
countriesFiltered:"(error during evaluation)"
countriesList:Array[242]
countriesSorted:Array[242]
countryCode:"RO"
hasEmptyPhone:true
hintValue:null
inputValue:null
isValid:undefined
otherCountries:"(error during evaluation)"
phoneNumberExample:"0712 034 567"
shouldChooseCountry:false
t:Object
countrySelectorError:"Choose country"
countrySelectorLabel:"Country code"
countrySelectorSearchPlaceholder:"Search country"
example:"Example:"
phoneNumberLabel:"Phone number"
CountrySelector:<MazSelect>
PhoneNumberInput:<MazInput id="MazPhoneNumberInput-12_phone_number">
```
Is there anything  I should do to make your library be aware when variable changes inside axios request?

**Comment by LouisMazel** [comment]
@lilian21 

I will fix it, I keep you posted

But verify your code, you have some mistake on it

**Comment by LouisMazel** [comment]
@lilian21  

I just released the [1.2.9](https://github.com/LouisMazel/maz-ui/releases/tag/v1.2.9) of [Maz UI](https://louismazel.github.io/maz-ui/) and the new version of [MazPhoneNumberInput](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input/)

Your issue is fixed :fire: 

**[Release Changelog](https://github.com/LouisMazel/maz-ui/releases/tag/v1.2.9)**

**Comment by lilian21** [comment]
I confirm, works like a charm! Thank you!

**Comment by lilian21** [comment]
:) I guess I didn't fully tested it earlier. It updates input but not 100% correctly, ex.:
Case 1:
1. `this.phone_number = '+447400123456'` (hardcoded) before calling axios request; (UK)
2. `this.phone_number = response.data.phone_number`  inside axios request // here number is '+390661969084'(IT) 
Result: 
![image](https://user-images.githubusercontent.com/4830532/86148000-bccb7300-bb02-11ea-9a24-3ea3d9405c9a.png)

Case 2:
1. `this.phone_number = null` (initialized in data)
2. `this.phone_number = response.data.phone_number` inside axios request // same number as above (IT)
Result:
![image](https://user-images.githubusercontent.com/4830532/86148322-2481be00-bb03-11ea-916f-d6cd543ad8b1.png)

**Comment by LouisMazel** [comment]
I'm working on it

Thanks again for your feedback :fire:

**Comment by LouisMazel** [comment]
It's really solved now in the **1.2.10** ! 

Let me know if you have another issues

Thanks

**[Release-1.2.10](https://github.com/LouisMazel/maz-ui/releases/tag/v1.2.10)**

**Comment by LouisMazel** [comment]
Test the new version [with this codesandbox](https://codesandbox.io/s/mazphonenumberinput-ekyd8?file=/src/App.vue)

**Comment by lilian21** [comment]
Yep, totally checked and works perfect! Thank you very much for your time..!!
