### ISSUE TITLE
Offical language for India

### ISSUE THREAD

**Issue by werty37** [LouisMazel/vue-phone-number-input#106]
It is factually incorrect to put Hindi script for India. Please use English. 

From Wikipedia, https://en.wikipedia.org/wiki/Languages_with_official_status_in_India#Official_languages_of_the_Union

> The Indian constitution, in 1950, declared Hindi in Devanagari script to be the official language of the union. Unless Parliament decided otherwise, the use of English for official purposes was to cease 15 years after the constitution came into effect, i.e., on 26 January 1965. The prospect of the changeover, however, led to much alarm in the non Hindi-speaking areas of India, especially Dravidian-speaking states whose languages were not related to Hindi at all. As a result, Parliament enacted the Official Languages Act, 1963, which provided for the continued use of English for official purposes along with Hindi, even after 1965.

**Comment by LouisMazel** [comment]
Hi @werty37,

What script are you talking about?
