### ISSUE TITLE
Change country code to match a pasted phone number (FEATURE REQUEST)

### ISSUE THREAD

**Issue by nigelmpofu** [LouisMazel/vue-phone-number-input#108]
## Is your feature request related to a problem? Please describe

When a number (containing the country code) is pasted, the country code is ignored. For example, if the United States (+1) phone number `+1 555 555 1234` is pasted into the phone number field while the country code is set to a different country, the pasted country code (+1) is ignored and the phone number is treated as part of the already set country code and only shows as `555 555 1234`.

## Describe the solution you'd like

Automatically switch the selected country code to match that of a pasted phone number if one is already provided. Using the example above, the country code should change to the United States (+1) to match the phone number.

## Additional context

Sample Screenshot when pasting `+15555551234`
![example](https://i.imgur.com/faUXHkT.png)

**Comment by LouisMazel** [comment]
Hi @nigelmpofu ,

This feature is available on the new version of this plugin on my new library Maz UI

- [MazPhoneNumberInput - Demo & Documentation](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input)
- [Maz UI](https://louismazel.github.io/maz-ui/)
- [Maz UI - Get started](https://louismazel.github.io/maz-ui/documentation/get-started)

Enjoy :)

**Comment by shaneqld** [comment]
Is vue-phone-number-input being deprecated in favor of MaxPhoneNumberInput?

**Comment by LouisMazel** [comment]
@shaneqld  

Yes, this plugin remains available but will no longer evolve

Test the new one of [Maz UI](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input/) on [Codesandbox](https://codesandbox.io/s/mazphonenumberinput-ekyd8)
