### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>' (BUG)

### ISSUE THREAD

**Issue by andrewhavens** [LouisMazel/vue-phone-number-input#109]
## Describe the bug

I'm trying to get started adding this package to my project.

## Steps to reproduce

Simply adding this line to my `application.js` pack fails to import:

```js
import VuePhoneNumberInput from 'vue-phone-number-input'
```

I see this in the browser:

```
Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Module.<anonymous> (vue-phone-number-input.common.js:5)
    at Module../node_modules/vue-phone-number-input/dist/vue-phone-number-input.common.js (vue-phone-number-input.common.js:17142)
    at __webpack_require__ (bootstrap:19)
    at Module../app/javascript/packs/application.js (application.js:4)
    at __webpack_require__ (bootstrap:19)
    at Object.0 (log.js:56)
    at __webpack_require__ (bootstrap:19)
    at bootstrap:83
    at bootstrap:83
```

## Expected behavior

Just want to import this so I can start using it.

## Screenshots

<img width="914" alt="Screen Shot 2020-07-01 at 4 52 20 PM" src="https://user-images.githubusercontent.com/446392/86301676-4c345d00-bbbb-11ea-88d5-4618e3982bfe.png">

## Device (please complete the following information)

- OS: Mac
- Browser: Chrome 83
- Package version: 1.1.9
- Rails app using Webpacker

## Additional context

Other packages:
```
    "lodash": "^4.17.4",
    "vue": "^2.6.11",
    "vue-cookie": "^1.1.4",
    "vue-easy-toast": "^1.0.2",
    "vue-loader": "^15.9.0",
    "vue-observe-visibility": "^0.3.1",
    "vue-resource": "^1.3.4",
    "vue-template-compiler": "^2.6.11",
    "vuelidate": "^0.5.0"
```

**Comment by LouisMazel** [comment]
@andrewhavens 

Nobody has this error, review your babel or webpack config

But you can test the new one on my new stand-alone components library: **[Maz UI](https://louismazel.github.io/maz-ui/)**

Many new features, better UI and better perf

**MazPhoneNumberInput: [Documentation & Demo](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input)**
**Demo on codesandbox: [HERE](https://codesandbox.io/s/mazphonenumberinput-ekyd8)**

**Comment by andrewhavens** [comment]
@LouisMazel Sure, I understand that it's probably an issue specific to my project's configuration, but I'm not sure what is causing it because I'm not very familiar with Babel or Webpack. I ended up going with https://github.com/EducationLink/vue-tel-input because I didn't need to change any configuration to get it to work.

**Comment by LouisMazel** [comment]
UI of vue-tel-input is really bad... Don't do that haha

Try to use: 

```js
const VuePhoneNumberInput = require ('vue-phone-number-input')
```

Otherwise look [this article](https://medium.com/@po_thiago/cannot-assign-to-read-only-property-exports-of-object-object-1d908589e135) or [this issue](https://www.google.com/search?q=TypeError%3A+Cannot+assign+to+read+only+property+%27exports%27+of+object&oq=TypeError%3A+Cannot+assign+to+read+only+property+%27exports%27+of+object&aqs=chrome..69i57j69i58.337j0j7&sourceid=chrome&ie=UTF-8)

**Comment by andrewhavens** [comment]
As mentioned in that first article you linked, it looks like adding `sourceType: 'unambiguous'` to my `babel.config.js` file fixed the problem. Thanks!
