### ISSUE TITLE
[Feature Request] Automatically recognizing the country code by phone number

### ISSUE THREAD

**Issue by shavidzet** [LouisMazel/vue-phone-number-input#11]
I'm excited and disappointed too about this feature 😭 

I think it's very important part for phone input component, also It improves user experience, when user just types number and component can automatically recognize the country code.

What you think about it? 🤔

**Comment by sombatos** [comment]
+1

See implementation here (parsePhoneNumberFromString): https://github.com/EducationLink/vue-tel-input/commit/c73d0099faabca80f831cc29857ea18a580e2682

**Comment by robinbuerkli** [comment]
Is there any update on this? I've implemented a very basic version based on the suggestion of @sombatos in my fork, but I doubt that doesn't interfere with other features. So did anyone familiar with the component pursued this request?

**Comment by LouisMazel** [comment]
Solved in 1.1.9

**RELEASE**: [https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.9](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.8)
