### ISSUE TITLE
flags z-index issue while select list of countries is open

### ISSUE THREAD

**Issue by EugeneVaida** [LouisMazel/vue-phone-number-input#112]
Using your control with vue formulate forms, and in form i need several rows with phone-number-input. And this problem occured after opening dropdown. See screenshot
![image](https://user-images.githubusercontent.com/36773117/87035335-da2eca00-c1f1-11ea-8db7-1b8e0b24350a.png)

After research of this problem possible solution may be like this : default display value for **maz-select__options-list** is display: none; and there is maz-flex class on this block that should set display: flex; and as chrome devtools shows it should work but there is small moment that display: flex; should be set dynamically

**Comment by LouisMazel** [comment]
Hi @EugeneVaida ,

This plugin is unmaintened now.  
Please use the new version in my new library **[Maz-Ui](https://louismazel.github.io/maz-ui/)**:
- **[[Documentation & Demo of MazPhoneNumberInput]](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input/)**
- **[[Codesandbox Demo + Implementation]](https://codesandbox.io/s/mazphonenumberinput-ekyd8?file=/src/App.vue)**

The bug you are reporting is not resolved yet, but I will fix it soon: 
- Your issue in the new repo: **[Issue](https://github.com/LouisMazel/maz-ui/issues/73)**

---

Enjoy some new features : 
- **Country auto-detect** with calling code
- **Search input** in list
- return **e.164** format in v-model when phone number is valid
- Better performance
- Better UI

**+ Many others components** with the same style

Let me know if you find bugs or if you have questions: [issues](https://github.com/LouisMazel/maz-ui/issues)

**Maz UI is a stand-alone components library for Vue.JS et Nuxt.JS**. With Babel, install easily and only the components you need without importing code you don't need
- **[Get-Started documentation page](https://louismazel.github.io/maz-ui/documentation/get-started)**
- **[Github](https://github.com/LouisMazel/maz-ui)**
- **[NPM](https://www.npmjs.com/package/maz-ui)**

**Comment by EugeneVaida** [comment]
Yes, i use this input from your new library, thanks for your response!
