### ISSUE TITLE
(BUG) Dropdown list ends up inside vuetify modals instead of exceeding it.

### ISSUE THREAD

**Issue by allanchua101** [LouisMazel/vue-phone-number-input#115]
When I place this awesome input component inside vuetify's modal component. The list stays inside.

![Sample](https://i.imgur.com/2Sz1b1B.png)

**Comment by LouisMazel** [comment]
Hi @allanchua101 

This bug comes from the Vuetify modal.
If you use the [Maz-UI modal](https://louismazel.github.io/maz-ui/documentation/maz-dialog), everything is ok

Thanks
