### ISSUE TITLE
(BUG) Country list close when clicking scroll bar

### ISSUE THREAD

**Issue by zozoh94** [LouisMazel/vue-phone-number-input#116]
Everything is in the title. I don't know why but when I click on the scroll bar the close event is emitted.

Thank you for your help.

**Comment by LouisMazel** [comment]
Hi @zozoh94,

Please use the new verison on VuePhoneNumberInput available on [**MazUI library**](https://maz-ui.com/) ==> [**MazPhoneNumberInput**](https://maz-ui.com/components/maz-phone-number-input)

VuePhoneNumberInput is unmaintained

**Comment by a92gerasimov** [comment]
Hi! Same issue with MazPhoneNumberInput. That happens when the phone number input is in a modal window.

**Comment by Unlimited23** [comment]
Has anyone fixed this? Why is it closed? The problem is still relevant.
