### ISSUE TITLE
(BUG) Update value with country code not works

### ISSUE THREAD

**Issue by dd-han** [LouisMazel/vue-phone-number-input#117]
## Describe the bug

Update component value with country code change phone number section, but country code section not.

## Steps to reproduce

 1. Go to [this sample code](https://jsfiddle.net/dd_han/qgopf1sm/)
 2. After render, result screen should show Japan phone number
 3. Wait for 1.5 second, a Taiwan phone number should replace original Japan phone
 4. Phone number change to Taiwan phone number, but Country code still keep in Japan

## Expected behavior

After 1.5 second wait, Country code and Phone number should both update (now only phone number update).

## Screenshots

![圖片](https://user-images.githubusercontent.com/5909203/88906143-a93e3400-d289-11ea-8d25-a1aba807af7d.png)

## Device (please complete the following information)

- OS: Windows 10
- Browser: Chrome 84, Firefox 78
- Package version: 1.1.9

## Additional context

[Related code here](https://github.com/LouisMazel/vue-phone-number-input/blob/master/src/VuePhoneNumberInput/index.vue#L217). But not sure country code overwrite by value is expected or not.

**Comment by LouisMazel** [comment]
Hi @dd-han,

This feature is available on the new version of this plugin on my new library Maz UI

- **[MazPhoneNumberInput - Demo & Documentation](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input)**
- **[Maz UI](https://louismazel.github.io/maz-ui/)**
- **[Maz UI - Get started](https://louismazel.github.io/maz-ui/documentation/get-started)**

Enjoy :)

**Comment by Pezhvak** [comment]
hey, in the new version it cannot detect the right country code. try: 989125555555, it should pick iran, but it doesn't. instead it picks up +1 for the country code
