### ISSUE TITLE
Country Selection is very bugged(BUG)

### ISSUE THREAD

**Issue by AllanOricil** [LouisMazel/vue-phone-number-input#122]
I added the component to nuxt and this happened. I don't have any custom CSS applied to the component.

![image](https://user-images.githubusercontent.com/55927613/93019453-05a5aa80-f5cf-11ea-8d3d-3af4ed1414e8.png)

When I use the maz-ui it works fine.

![image](https://user-images.githubusercontent.com/55927613/93020091-2b34b300-f5d3-11ea-8ed0-cc4c2734d16a.png)

**Comment by Julien-R44** [comment]
I had the same bug, the issue was coming from this library : https://github.com/serebrov/emoji-mart-vue
They was modifying the css of .vue-recycle-scroller class globaly, which is part of https://github.com/Akryum/vue-virtual-scroller that vue-phone-number-input use too.
So check your css imports and try disabling them one by one

**Comment by AllanOricil** [comment]
Thanks @Julien-R44 but I end up using another lib.

**Comment by bendiy** [comment]
@Julien-R44 I'm seeing the same issue.
Did you find a workaround to allow `emoji-mart-vue` and `vue-phone-number-input` to work together?

**Comment by Julien-R44** [comment]
Only solution I see : fork the library, update it, and I think you can send a pull request 😃 
I haven't had time to do it yet

**Comment by Julien-R44** [comment]
@bendiy Only solution I see : fork the library, update it, and I think you can send a pull request 😃
I haven't had time to do it yet

**Comment by bendiy** [comment]
@Julien-R44 Thanks. I ended up removing `emoji-mart-vue` and switching to `vue-twemoji-picker` with minimal changes to my codebase.
https://kevinfaguiar.github.io/vue-twemoji-picker/docs/getting-started/
