### ISSUE TITLE
Country select have problem while using in overflow:hidden (BUG)

### ISSUE THREAD

**Issue by dinlyhor** [LouisMazel/vue-phone-number-input#123]
## Describe the bug

The drop-down of country selection is hidden some path while we use in the table have scrolling.
The drop-down does not display on the table that has scroll.

![image](https://user-images.githubusercontent.com/39936398/93187914-88af3800-f76a-11ea-9deb-c388bb6b2cba.png)

![image](https://user-images.githubusercontent.com/39936398/93188903-c2347300-f76b-11ea-8b5d-00d54948734b.png)

**Comment by LouisMazel** [comment]
Hello @dinlyhor, 

It's normal... You must not use an "overflow: hidden" or enlarge the area
