### ISSUE TITLE
Can't do programmatically .focus() on the component

### ISSUE THREAD

**Issue by chemb77** [LouisMazel/vue-phone-number-input#124]
I've tried to use $refs for the component. 
this.$refs.phone.focus() - focus is not a function.

Also, $refs for the component is undefined. 
this.$refs.phone.$refs
{CountrySelector: undefined,
PhoneNumberInput: undefined}

**Comment by LouisMazel** [comment]
Hi @chemb77,

You have to find the input of PhoneNumberInput, so : 

```js
<template>
  <MazPhoneNumberInput
    ref="Phone"
    v-model="phoneNumber"
  />
</template>

<script>
export default {
  name: 'YourParentComponent',
  data () {
    return {
      phoneNumber: null
    }
  },
  mounted () {
    this.focusPhoneNumberInput()
  }
  methods: {
    async focusPhoneNumberInput () {
      await this.$nextTick() // wait until the $refs are available
      this.$refs.Phone.$refs.PhoneNumberInput.$el.querySelector('input').focus()
    }
  }
}
</script>
```

In this example, I trigger the methods `focusPhoneNumberInput` on `mounted`

**Comment by LouisMazel** [comment]
In the future, report your issue about `MazPhoneNumberInput` on [maz-ui repo issues](https://github.com/LouisMazel/maz-ui/issues)
