### ISSUE TITLE
(QUESTION) How to get in v-model formatNational number

### ISSUE THREAD

**Issue by sshNkt** [LouisMazel/vue-phone-number-input#128]
How to get number with country code in v-model

**Comment by LouisMazel** [comment]
This feature is available in the new version of this plugin on **[Maz-UI](https://louismazel.github.io/maz-ui/)**

- MazPhoneNumberInput: **[Documentation](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input)**
- **[Get Started](https://louismazel.github.io/maz-ui/documentation/get-started)**
