### ISSUE TITLE
Allow to override font-family

### ISSUE THREAD

**Issue by ajcastro** [LouisMazel/vue-phone-number-input#135]
Is there a way to override font-family?

**Comment by LouisMazel** [comment]
Use the new version of this component present into **[Maz-UI](https://github.com/LouisMazel/maz-ui)**:
- **[Get Started](https://louismazel.github.io/maz-ui/documentation/get-started)**
- **[Theming](https://louismazel.github.io/maz-ui/documentation/theme)**: See **"typo"** in config object
- **[MazPhoneNumberInput](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input)**: is the new version

DEMO:
- **[DEMO / Codesandbox](https://codesandbox.io/s/mazphonenumberinput-gjfsd)**

**Comment by LouisMazel** [comment]
Otherwise, with VuePhoneNumberInput you can override the font-family by CSS

Ex: 
```css
.input-tel {
    font-family: <YOUR_FONT_FAMILY>, sans-serif;
}
```
