### ISSUE TITLE
How to change the example format?

### ISSUE THREAD

**Issue by waziaq** [LouisMazel/vue-phone-number-input#137]
In Props API have to disable the example text. But how to change the example base on the region? have this function or not?

" Example: 012-345 6789 " want to change to " Example: 12-345 6789 "

**Comment by LouisMazel** [comment]
Hi @waziaq,

No sorry, you can't do that. The example is provided by the library [libphonenumber-js](https://www.npmjs.com/package/libphonenumber-js). 

You can only disable it.
