### ISSUE TITLE
How to hide the focus border of input fields?

### ISSUE THREAD

**Issue by lorro** [LouisMazel/vue-phone-number-input#16]
Hi,

Do you have a suggestion how we could hide the border that appears whenever we focus one of the 2 fields (country selector & input field). I have attached a screenshot.
It gets added by an !import inline-style so I can't really set the border to 0 by overriding the css.

I restyled the component a bit for my usecase so it fits better within my vuetify application, but I don't really like the orange border :-)

![2019-05-27_173836](https://user-images.githubusercontent.com/977617/58429556-8c670900-80a6-11e9-8a12-b4bfaae085d9.jpg)

Thanks

**Comment by InfCesar** [comment]
You might want to use the :color and :valid-color props to change it.

**Comment by kagankorkmaz** [comment]
@lorro how did you arranged the border-width whne focued?
