### ISSUE TITLE
(BUG) vue-phone-number-input is returning only the phone number string instead of Object with country code

### ISSUE THREAD

**Issue by venkatesh81290** [LouisMazel/vue-phone-number-input#161]
## Describe the bug

vue-phone-number-input v1.1.10 is returning only the entered phone number as string string instead of Object with country code

## Steps to reproduce

https://codesandbox.io/s/vue-tel-input-with-vue-form-generator-forked-8gonw?file=/src/main.js

Please refer the attached codesandbox link where the issue is reproduced.

## Expected behavior

v-model should set Object with countryCode, phoneNumber, isValid, etc keys.

**Comment by LouisMazel** [comment]
Hi @venkatesh81290 ,

The **v-model** is the full phone number that you should save

To get other data, use the event **@update** : check this [DEMO](this https://codesandbox.io/s/vue-tel-input-with-vue-form-generator-forked-hwnic?file=/src/App.vue)
