### ISSUE TITLE
When will you have a vue3 version?

### ISSUE THREAD

**Issue by crazyzpl** [LouisMazel/vue-phone-number-input#170]
My vue3 project really need your phone number input component, but this component's vue version is 2.x. So when will you start a vue3.x version?

**Comment by LouisMazel** [comment]
Hi @crazyzpl ,

This plugin is unmaintained. 
The good version for Vue2 is in maz-ui: https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input, and you have more features on it

I'm currently working on the version for Vue 3, it's in beta : https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input.html
Be careful, so many things can change in the futur
