### ISSUE TITLE
Hello, when I registered vue-phone-number-input multiple times on different components on a page, countries-list did not expand properly.

### ISSUE THREAD

**Issue by lookCLZ** [LouisMazel/vue-phone-number-input#18]

**Comment by LouisMazel** [comment]
Hi,

As you can see on the demo, you must provide differents id to each component

**Comment by lookCLZ** [comment]
@LouisMazel thank you very much O(∩_∩)O

**Comment by mberkeland** [comment]
Perhaps you should put this info on the READ.ME or someplace obvious?  It is a really important bit of info (the absolute NEED for IDs when using more than one of the control).  The behavior is very sporadic and unexpected without it, and it is not obvious from the symptoms where to look for the issue...  thanks!!!
