### ISSUE TITLE
(BUG) zoom-in Safari

### ISSUE THREAD

**Issue by rmassimi** [LouisMazel/vue-phone-number-input#180]
Hello,
with iPhone using Safari, when I tap on country select or tap on input Phone Number, page now stays zoomed-in.

## Steps to reproduce
 1. Go to demo https://louismazel.github.io/vue-phone-number-input/
 2. select a country or insert a phone number'
 3. See page zoomed

## Device 
- Device (Iphone-8 and plus)
- OS:  iOS
- Browser: Safari
- Package version: 15.3

Thank you,

Roberto

**Comment by LouisMazel** [comment]
@rmassimi,

This is a bug in the viewport metadata of the HTML page, not the plugin itself.

To fix it, you can add something like this : 
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
```

BE careful, this library is deprecated. You should use the [maz-ui](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input) for Vue.JS 2 et [maz-ui-3](https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input.html#basic-usage) fro Vue.JS 3 (beta version)

If you have any question, don't hesitate to ask me :)
