### ISSUE TITLE
(FEATURE REQUEST) - Quick Question

### ISSUE THREAD

**Issue by rak-ryan** [LouisMazel/vue-phone-number-input#181]
Hello,

Awesome work you have done here! I have one quick question...

Is this library deprecated? Or is it still being supported along side MAZ-UI?

Thank you so much for your good work!

r.

**Comment by LouisMazel** [comment]
Hello @rak-ryan, 

Thank you so much ! 

Yep, this library is deprecated. You should use the [maz-ui](https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input) for Vue.JS 2 et [maz-ui-3](https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input.html#basic-usage) fro Vue.JS 3 (beta version)

If you have any question, don't hesitate to ask me :)
