### ISSUE TITLE
为什么台湾国旗不是中国国旗，请尽快修正(BUG)

### ISSUE THREAD

**Issue by MajorMayer** [LouisMazel/vue-phone-number-input#194]
为什么台湾国旗不是中国国旗，请尽快修正

**Comment by LouisMazel** [comment]
Hi, 

Can you translate it in English please ?

**Comment by nmsl8848** [comment]
Why is the TaiWan flag not the Chinese flag,or mark it 中国台湾? please fix it.

**Comment by nmsl8848** [comment]
if u have diffrent political stand, please tell us.

**Comment by LouisMazel** [comment]
**Warning**: This plugin is unmaintained. 

But in the new version of this plugin available for Vue 3 available [here](https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input), it's absolutely not a political or personal choice, the flag is auto-generated with the country code "TW" by using the unicode associated in your browser or your mobile phone.
Check the code here: https://github.com/LouisMazel/maz-ui/blob/master/packages/lib/modules/helpers/locale-to-unicode-flag.ts
