### ISSUE TITLE
Doesn't work in IE 11

### ISSUE THREAD

**Issue by jacobg** [LouisMazel/vue-phone-number-input#2]
If you go to https://louismazel.github.io/vue-phone-number-input/, the page doesn't render, and you'll see this error:
`Multiple definitions of a property not allowed in strict mode`

The error is in the component itself, because my own app using this component also has the error.

**Comment by jacobg** [comment]
The problem is that in the umd dist file on line 1901, there is a duplicated `is-focused` attribute:
```
var render = function () {var _vm=this;var _h=_vm.$createElement;var _c=_vm._self._c||_h;return _c('div',{ref:"parent",staticClass:"field",class:[{
    'is-focused': _vm.isFocus,
    'has-value': _vm.value,
    'has-error': _vm.error,
    'is-disabled': _vm.disabled,
    'is-dark': _vm.dark,
    'is-focused': _vm.valid,
    'has-hint': _vm.hint && !_vm.value
  }, _vm.size],...
```

I don't know why though, because the source code doesn't have that:
```
  <div
    ref="parent"
    v-click-outside="onBlur"
    :class="[{
      'is-focused': isFocus,
      'has-value': value,
      'has-hint': hint,
      'has-error': error,
      'is-disabled': disabled,
      'is-dark': dark,
      'no-flags': noFlags
    }, size]"
    class="field country-selector"
    @click="onFocus"
    @keydown="keyboardNav"
  >
```

Any ideas?

**Comment by jacobg** [comment]
I just saw the issue is in your vue-input-ui project:
https://github.com/LouisMazel/vue-input-ui/issues/1

**Comment by LouisMazel** [comment]
It's fixed here too ! 
Let me know if all is good

Thanks again :)

**Comment by jacobg** [comment]
Thanks! Much appreciated!
