### ISSUE TITLE
[Feature Request] Option to show the Country Code in the flags/country pulldown

### ISSUE THREAD

**Issue by mberkeland** [LouisMazel/vue-phone-number-input#20]
It might be very helpful to show the country code as well as the flag/country name when using the Country Code pulldown.  It displays once a country is chosen, but having it also display in the list would be nice.  This component is AWESOME!

**Comment by LouisMazel** [comment]
show-calling-code option is available on [1.0.6 version](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.0.6)
