### ISSUE TITLE
I cannot import to my NUXT project

### ISSUE THREAD

**Issue by yothin-workout** [LouisMazel/vue-phone-number-input#25]
Here is my set up : 

1.  npm i --save vue-phone-number-input
2. create vue-phone-number-input.js  to  /plugins 
 `import VuePhoneNumberInput from "vue-phone-number-input"
 import "vue-phone-number-input/dist/vue-phone-number-input.css"
 Vue.component("vue-phone-number-input", VuePhoneNumberInput)`

3. add  ~nuxt.config.js 
` plugins: [
    "~/plugins/vue-phone-number-input"
  ],`
4. in my component 
`<VuePhoneNumberInput v-model="phone"/>`

Vue warning : 
`[Vue warn]: Unknown custom element: <VuePhoneNumberInput> - did you register the component correctly? For recursive components, make sure to provide the "name" option.`

**Comment by exzib** [comment]
How did you solve this?

**Comment by habibiazmi123** [comment]
just change:
Vue.component("vue-phone-number-input", VuePhoneNumberInput)
to
Vue.component("VuePhoneNumberInput", VuePhoneNumberInput)

it's work for me

**Comment by ajaymarathe** [comment]
> just change:
> Vue.component("vue-phone-number-input", VuePhoneNumberInput)
> to
> Vue.component("VuePhoneNumberInput", VuePhoneNumberInput)
> 
> it's work for me

Yeah, it's working. thanks.
