### ISSUE TITLE
Auto choise country

### ISSUE THREAD

**Issue by powerlimit** [LouisMazel/vue-phone-number-input#27]
hello! nice plugin. 

can I automatically set the country code when a user visits the site? I have an API to get the user's country. and I would like to automatically set the country based on the results of this api

**Comment by sombatos** [comment]
See https://github.com/LouisMazel/vue-phone-number-input/issues/30

**Comment by LouisMazel** [comment]
Hi, 

I just fixed this bug (it's a reactivity prob with the props)
https://github.com/LouisMazel/vue-phone-number-input/commit/d17c119d1bcb0673d35e1782537e382e4ba6d7f2

I will release this today !

Thanks for your feedback
