### ISSUE TITLE
Once you have input an area code - you can not delete it

### ISSUE THREAD

**Issue by croossin** [LouisMazel/vue-phone-number-input#29]
If you enter the first 3 digit area code, you will not be able to backspace and delete it.
![Screen Shot 2019-07-22 at 7 31 12 AM](https://user-images.githubusercontent.com/7241069/61640737-b6761b00-ac52-11e9-8d2a-99c36ab34a72.png)

**Comment by croossin** [comment]
Any update to this?

**Comment by daniel-stelle** [comment]
It looks like you can delete it, you just have to move the cursor inside the parentheses.  Still isn't very ideal though.

**Comment by LouisMazel** [comment]
Hi, 

Thanks for your feedback ! I will fix it soon !

**Comment by i-ira** [comment]
> Hi,
> 
> Thanks for your feedback ! I will fix it soon !

this bug is very bothersome, hopefully you patch it soon! I love the component btw!

**Comment by leoclipet** [comment]
Any news on this one ?

**Comment by LouisMazel** [comment]
Hello ! 

I just fixed this and it's released !
https://github.com/LouisMazel/vue-phone-number-input/releases/tag/0.2.4

Enjoy and give a feedback if something is wrong
