### ISSUE TITLE
Poor performance on mobile

### ISSUE THREAD

**Issue by sombatos** [LouisMazel/vue-phone-number-input#32]
On mobile phone in Chrome it takes at least 3 seconds to open countries dropdown first time (https://louismazel.github.io/vue-phone-number-input/). Maybe there is a way to improve it, some kind of precaching, etc?

**Comment by NicTorgersen** [comment]
Found a similar problem in the Opera browser. It takes a while before you are allowed/able to scroll.

**Comment by LouisMazel** [comment]
Solved on 1.1.0 version

[Changelog release](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.0)
[Pull request about virtual dom list](https://github.com/LouisMazel/vue-phone-number-input/pull/67)
