### ISSUE TITLE
Dark theme incompatibility with disabled

### ISSUE THREAD

**Issue by frossigneux** [LouisMazel/vue-phone-number-input#33]
Dark theme works perfectly.
However, setting disabled prop to true disable the dark theme.

![1](https://user-images.githubusercontent.com/739143/64486835-b34ee280-d232-11e9-8c44-cfaaa3deeb68.png)

As quick and dirty fix, I use `pointer-events: none` to simulate a read only field:
![2](https://user-images.githubusercontent.com/739143/64486838-b944c380-d232-11e9-9553-42f124a64b74.png)

**Comment by LouisMazel** [comment]
Hi, 

Thanks you ! I will fix it soon !
