### ISSUE TITLE
Unknown custom element: <vuephonenumberinput>

### ISSUE THREAD

**Issue by Evanzsnr** [LouisMazel/vue-phone-number-input#35]
When I try to use this plugin in laravel 5.8, I get an error saying the element is not know recognize the custom element. Is there an issue with the element or am using it wrongly?

**Comment by LouisMazel** [comment]
Hi, 

Can you show me your code ?

Thanks

**Comment by Evanzsnr** [comment]
Hello,

First I installed using npm, then imported the plugin in app.js as shown
below
import VuePhoneNumberInput from 'vue-phone-number-input';

Vue.component('vue-phone-number-input', VuePhoneNumberInput);

Next I also imported it in app.css as shown below
@import 'node_modules/vue-phone-number-input/dist/vue-phone-number-input';

Then I added the input component in my form
<div class="field">
                            <label for="photo" class="label">Profile Picture
</label>
                            <input type="file" name="photo" class=
"file-label">
                            @if ($errors->has('photo'))
                                <span class="help-block">
                                    <p class="help is-danger"><strong>{{
$errors->first('photo') }}</strong></p>
                                </span>
                            @endif
                        </div>

                        <div class="field">
                            <label for="notes" class="label">Notes</label>
                            <b-input name="notes" maxlength="200" type=
"textarea" value="{{ old('notes') }}"></b-input>
                            @if ($errors->has('notes'))
                                <span class="help-block">
                                    <p class="help is-danger"><strong>{{
$errors->first('notes') }}</strong></p>
                                </span>
                            @endif
                        </div>

                        <VuePhoneNumberInput v-model="phone_number" />

                        <div class="field" style="margin-top: 10px;">
                            <b-button size="is-normal" class=
"is-link is-outlined is-fullwidth"
                                icon-left="account-check-outline"
native-type="submit">
                                Save Client
                            </b-button>
                        </div>

On the page where I have the form, I have a vue instance since I have other
vue components working well, but when I load my page after adding the phone
number component, I get the error saying the component is not known.

**Comment by nperegrine** [comment]
Hey, @Evanzsnr Ran into this same issue.

Not sure exactly why, but when I changed the component name inside my vue.js files from: 

`<VuePhoneNumberInput />`

to:

`<vue-phone-number-input />` 

it works, hope this might help :)

**Comment by Evanzsnr** [comment]
Thanks @nperegrine , Your solution worked for me.

**Comment by Evanzsnr** [comment]
Hello,

How do I access the object that contains the data as displayed in the demo?

Thanks

**Comment by nperegrine** [comment]
Hi @Evanzsnr 

If I understand what you're asking properly, here's how I got the data as displayed in the demo: 

I used the `@update` event to call a method `updatePhoneNumber` and used the emitted event to get the data I wanted.
```
 <vue-phone-number-input
            v-model="phone"
            :required="true"
            default-country-code="CM"
            @update="updatePhoneNumber"
          />
```
Below's my @updatePhoneNumber method I used to get the data from the emitted event:

```
  /**
     * Update phone number
     */
    updatePhoneNumber(data) {
      this.formatted_number = data.formattedNumber
      this.national_number = data.nationalNumber
    }
```

You can use the data object to get whatever prop you desired as shown in the demo.

Hope this helps 😀

**Comment by Evanzsnr** [comment]
Thank you so much, it works perfectly.

**Comment by Evanzsnr** [comment]
Hello,

I have another question, how can I set the value for the phone number as
the formatted number?

I am failing to bind the data.formattedNumber to the v-model value.

Thanks
