### ISSUE TITLE
Edit

### ISSUE THREAD

**Issue by digi-sagar** [LouisMazel/vue-phone-number-input#36]
On editing, the country code does not match
![image](https://user-images.githubusercontent.com/56542049/66746022-46b4ac80-ee9e-11e9-97ae-5ffa63909d00.png)

**Comment by LouisMazel** [comment]
Hi, 

You should use a number without indicative number (+91)

**Comment by digi-sagar** [comment]
Thank you, Louis, but in doing so, how do I specify the country code and flag? It is not retrieving yet.
The selected country was India.
![image](https://user-images.githubusercontent.com/56542049/66797732-68a74100-ef29-11e9-9d75-2a2e01759f04.png)
