### ISSUE TITLE
Add ability to hide country code component

### ISSUE THREAD

**Issue by burdenbound** [LouisMazel/vue-phone-number-input#46]
I only need to validate phone numbers against a single country. It would be nice if I could set a default country and hide the country code component altogether.

**Comment by LouisMazel** [comment]
Hi, 

Nice idea, I will implement this feature soon

Thanks

**Comment by LouisMazel** [comment]
It's add into `0.2.7` version

[Release 0.2.7](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/0.2.7)
