### ISSUE TITLE
Class is-focused stays if number is valid

### ISSUE THREAD

**Issue by NicTorgersen** [LouisMazel/vue-phone-number-input#47]
The class `is-focused` stays after phone number is validated/valid, which makes things look a little weird in my example (here I have clicked off the component, so it shouldn't be focused):
![Screen Shot 2019-11-04 at 11 28 07](https://user-images.githubusercontent.com/1327106/68114394-33718b80-fef6-11e9-9995-edf06e5e412e.png)

I've fixed it locally by using :focus-selector, but is-focused shouldn't really stay after the element is not focused.

**Comment by LouisMazel** [comment]
It's fixed into `0.2.7` version

[Release 0.2.7](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/0.2.7)
