### ISSUE TITLE
Country code is showing 2 times in input field

### ISSUE THREAD

**Issue by HamzaAhmad932** [LouisMazel/vue-phone-number-input#52]
i have an issue, please help me to figure out the problem.

i have a phone number value stored in DB as "+92 322 3661422", when i fetch the edit phone number form, vue-phone-number-input does not parsing the country code from the v-model and showing country code 2 times.
please see attachment

![issue](https://user-images.githubusercontent.com/32592510/68231984-ec7eb580-001d-11ea-8688-c5ffe48e7abf.png)

**Comment by NicTorgersen** [comment]
I had a similar issue. Instead of setting the value directly with `v-model` I needed to first parse the phone number using `parsePhoneNumberFromString` from the `libphonenumber-js`-library and then use `emitValues` from the `vue-phone-number-input` base component in order to trigger the validation.

An example is
```vue
<template>
    <div>
        <VuePhoneNumberInput v-model="phoneNumber" ref="vuePhoneNumberInput"></VuePhoneNumberInput>
    </div>
</template>
<script>
import Vue from 'vue'
import { parsePhoneNumberFromString } from 'libphonenumber-js'

export default Vue.extend({
    props: {
        initialPhoneNumber: String,
    },
    data() {
        return {
            phoneNumber: "",
        }
    },

    mounted() {
        this.setDefaults()
    },

    methods: {
        setDefaults() {
            let parsedPhoneNumber = parsePhoneNumberFromString(this.initialPhoneNumber, 'NO' /* your default supported country, e.g. NO */)

            if (parsedPhoneNumber) {
                this.$nextTick(() => {
                    this.$refs.vuePhoneNumberInput.emitValues({
                        countryCode: parsedPhoneNumber.country,
                        phoneNumber: parsedPhoneNumber.nationalNumber,
                    })
                })
            }
        }
    },
})
</script>
```

Hope this helps.
