### ISSUE TITLE
In IE 11, cannot change country code unless phone number is entered

### ISSUE THREAD

**Issue by NicTorgersen** [LouisMazel/vue-phone-number-input#53]
A coworker of mine on Windows reported an issue with IE 11 and changing country, you can only change it once, then you're unable to unless you start typing a phone number.

While the phone number is present, you are able to change country freely like in any other browser, but removing it will return back to not being able to change country.

Did not report any console errors.

**Comment by LouisMazel** [comment]
I can't reproduce this bug en IE11, it's work fine on 1.0.5 version 

![demo](https://d1l3wite3674hm.cloudfront.net/19jk%2Fpreview%2F29511541%2Fmain_large.gif?response-content-disposition=inline%3Bfilename%3D%22main_large.gif%22%3B&Expires=1574370971&Signature=caIvZ7UTfmnSx5YfP5dShiQkYM1Gb4O4VQIFNu56~BAfWAnnjNFlL7yb3N5LRT40h0RwSIL5IxpRGqclJbYJAvlwmxGtLAvNi9ebXlir-X7BgF3t4oRiZ6trMmW9KFJgFvBEfzjuy0b0cwEUP41rCuwYYBhSJdgFK76naMznYxRhrne0VGUSquQTjCIGzyDUjMUDzb2c8qfT3iP8frCsy8SPbzniphPYA4ti4otxKmfZp35Zo4sgd6nKo6M5HmVh1wjYG7o9qG37uUKRUb-ypH1cxVphrbiO7w3Dv2ZQT0mzeuVTD2XXvNva3Lfo-6FK1eHlPpJ3SgpN1quz2f8NsA__&Key-Pair-Id=APKAJT5WQLLEOADKLHBQ)
