### ISSUE TITLE
Class lm-text-danger stays after field is valid

### ISSUE THREAD

**Issue by NicTorgersen** [LouisMazel/vue-phone-number-input#55]
I've set the :error-prop because I needed to do some custom validation, however I found that the label is still red even after the component has successfully validated the input.

![Screen Shot 2019-11-14 at 13 15 58](https://user-images.githubusercontent.com/1327106/68856977-113ff080-06e2-11ea-9035-58c7d223e7c2.png)

I feel like `.lm-text-danger` should only be set if  `isValid` is false and `error` is true, not just if `error` is true (I'm just making an assumption that that's how it's  being done now). Or alternatively override the CSS for `.lm-text-danger` when is-valid is present (which is how I solved it).

**Comment by LouisMazel** [comment]
Solved on ![1.0.5](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.0.5)

**Comment by NicTorgersen** [comment]
Elegant solution, loving this component.
