### ISSUE TITLE
nvalid prop: type check failed for prop "preferredCountries".

### ISSUE THREAD

**Issue by ricardo17coelho** [LouisMazel/vue-phone-number-input#56]
Expected Array, got String with value "['FR', 'BE', 'DE']".

![image](https://user-images.githubusercontent.com/37732431/69529630-f2a6e880-0f70-11ea-8f88-a90fa90197ac.png)

**Comment by esalitrynskiy** [comment]
It is impolite to close an issue and not write a solution.

**Comment by esalitrynskiy** [comment]
Solution: 

`:preferred-countries="['RU']"`

**Comment by LouisMazel** [comment]
> It is impolite to close an issue and not write a solution.

@esalitrynskiy He closed his own request, he has found the solution
