### ISSUE TITLE
[Bug] Only countries feature not working

### ISSUE THREAD

**Issue by michieriffic** [LouisMazel/vue-phone-number-input#6]
I've tried working on the only-countries attribute and it seems that it is having issues.

CODE:
![screen shot 2019-03-01 at 6 19 28 pm](https://user-images.githubusercontent.com/12575688/53631981-c57e1180-3c4e-11e9-9708-485fb938c253.png)

RESULT:
![screen shot 2019-03-01 at 6 19 19 pm](https://user-images.githubusercontent.com/12575688/53631988-c9119880-3c4e-11e9-9ded-83a6a815afc9.png)

**Comment by LouisMazel** [comment]
You should use this syntax : `:only-countries="['FR', 'BE', 'DE']"` (with `:`)

Best

**Comment by michieriffic** [comment]
Thanks @LouisMazel :)
