### ISSUE TITLE
Payload

### ISSUE THREAD

**Issue by Ochieng424** [LouisMazel/vue-phone-number-input#62]
How do i access the payload data "isValid" to make sure that the value input must be valid before moving to the next step

**Comment by LouisMazel** [comment]
By the event `@update`, in the payload you have the `isValid` key. Return `true` or `false`

Ex : 

```html
<VuePhoneNumberInput v-model="yourValue" @update="showPayload" />
```

```js
export default {
  [...]
  methods: {
    showPayload (payload) {
      console.log(payload.isValid)
    }
  }
  [...]
}
