### ISSUE TITLE
[FEATURE REQUEST] Port to NativeScript Vue

### ISSUE THREAD

**Issue by dosomder** [LouisMazel/vue-phone-number-input#66]
## Is your feature request related to a problem? Please describe

I want to use a phone number input in NativeScript Vue but there is no such module.

## Describe the solution you'd like

Maybe it would be possible to port this module to NativeScript. Most likely just the elements need to be changed (e.g. `<div>`, etc.)

## Describe alternatives you've considered

There is no alternative yet.

**Comment by LouisMazel** [comment]
I don't have time for that sorry
