### ISSUE TITLE
Getting Wrong Country Code Selected

### ISSUE THREAD

**Issue by hitesh399** [LouisMazel/vue-phone-number-input#68]
## Description

Getting Wrong Country Code Selected, It is happened after some time When you start the play with phone number.

## Steps to reproduce
Example:

 1. Click on country list dropdown
 2. Start typing like sin, ind
 3. Select a country
 4. reopen country list by clicking on dropdown
 5. Select any country then you will not get expected result. like if you select India then the random code will reflect on page.   

## Expected behavior
Same country code should be displayed after selecting from dropdown

## Screenshots

![ezgif-4-cb0c6050c5e5](https://user-images.githubusercontent.com/15153925/71622814-68504500-2bfe-11ea-9bd8-fa47772483f9.gif)

## Device 

- OS: iOS
- Browser: Chrome 75,

**Comment by LouisMazel** [comment]
Hi, 

Thanks for your feedback. It's fixed on 1.1.1 version. 

If you want to see the code change: https://github.com/LouisMazel/vue-phone-number-input/commit/cc098a36ee5d50540f4efa03e367f22b80d7ca5a
