### ISSUE TITLE
Starting with version 0.2.5 using vue-phone-number-input in a component causes an error

### ISSUE THREAD

**Issue by StanlyShauro** [LouisMazel/vue-phone-number-input#69]
I include the  VuePhoneNumberInput inside another component:

```
...
<script>

  import VuePhoneNumberInput from 'vue-phone-number-input'

  export default {
    components: {
      vphone: VuePhoneNumberInput,
...
```

This causes the next error:

`"export 'default' (imported as 'VuePhoneNumberInput') was not found in 'vue-phone-number-input'`

It happens with version 0.2.5 and higher up to last release.

**Comment by LouisMazel** [comment]
Hmmm... All versions ? 
It's certainly because of your configuration, I can't do something for you, all work weel for me et everyone. 

See you webpack or node config

**Comment by Gonzalogdlr** [comment]
Hi I had the same problem, in my case I was using webpacker in rails, I solved it by putting:

const { environment } = require('@rails/webpacker')
environment.loaders.delete('nodeModules')

In my config/webpack/environment.js
