### ISSUE TITLE
Clicking a flag submits a form

### ISSUE THREAD

**Issue by MLDMoritz** [LouisMazel/vue-phone-number-input#70]
If you click on a flag it submits the form that is parent to the element.

https://github.com/LouisMazel/vue-phone-number-input/commit/b0302557fb01bfe7290c4adfa64cceee3737431f#r36668986

**Comment by LouisMazel** [comment]
Solved in [1.1.2](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.2)
