### ISSUE TITLE
Passing v-model with country code fails

### ISSUE THREAD

**Issue by MLDMoritz** [LouisMazel/vue-phone-number-input#71]
When you pass a phonenumber with country code the component doesn't behave like it should (Select correct country in list, strip countrycode and display correctly)

**Comment by altin-at-casengo** [comment]
@LouisMazel this is not an enhancement, it is most definitely a bug. I think this should be prioritized.

**Comment by LouisMazel** [comment]
Solved in 1.1.8

**RELEASE CHANGELOG**: [https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.8](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.8)
