### ISSUE TITLE
Unable to set placeholder

### ISSUE THREAD

**Issue by jmdrew** [LouisMazel/vue-phone-number-input#73]
`<VuePhoneNumberInput
                    placeholder="Place Holder Text"
                  ></VuePhoneNumberInput>`

Unable to change the place holder attribute. 
"version": "1.0.1",

**Comment by LouisMazel** [comment]
Hi, 

You should use `label="Your label & placeholder"` :)

**Comment by suddham** [comment]
> Hi,
> 
> You should use `label="Your label & placeholder"` :)

Hi can this be added to the docs?

**Comment by DipoAreoye** [comment]
Does this still work? label prop doesn't seem to update placeholder

**Comment by LouisMazel** [comment]
@DipoAreoye  

In the last versions the api has change. Please use `placeholder="Your label & placeholder"` now :)

**Comment by MelonSmasher** [comment]
> @DipoAreoye
> 
> In the last versions the api has change. Please use `placeholder="Your label & placeholder"` now :)

This is not working for me. I just installed the package from NPM.

```js
<VuePhoneNumberInput placeholder="Your label & placeholder"/>
```

<img width="513" alt="Screen Shot 2020-12-04 at 7 42 01 PM" src="https://user-images.githubusercontent.com/1491053/101228228-ca17fb00-3668-11eb-89af-f19264a4cebf.png">

Am I doing something wrong? Anyway thanks for this package It's great!

**Comment by owen800q** [comment]
same issue

**Comment by vtolochk** [comment]
Seems it doesn't work anymore

Workaround:
```
   mounted() {
      const input = document.querySelector('.input-tel__input');

      input.placeholder = "Your placeholder";
   }
```
