### ISSUE TITLE
Smaller css file

### ISSUE THREAD

**Issue by alexdpoon** [LouisMazel/vue-phone-number-input#74]
Component works well, but the css file is 435k. I think the main reason is the base64 images of the country flags.  It's making my bundle size too large.

It would be great if you could use unicode country flags instead and get rid of the images -- http://xahlee.info/comp/unicode_flags.html

**Comment by LouisMazel** [comment]
Hi, 

Thanks for your help ! I change the base64 image for a `flags.png` and it's really lighter now ! 

432Kb to 120Kb:
<img width="519" alt="Capture d’écran 2020-01-10 à 15 49 24" src="https://user-images.githubusercontent.com/12446546/72161970-62f2b780-33c1-11ea-8b53-4b906817a4eb.png">
<img width="505" alt="Capture d’écran 2020-01-10 à 15 49 55" src="https://user-images.githubusercontent.com/12446546/72161972-638b4e00-33c1-11ea-955e-cf7bda3f7556.png">

Maybe I can use unicode later to have a better CSS file size. Thanks.
