### ISSUE TITLE
Country Code List Button Define their type As "Button"

### ISSUE THREAD

**Issue by hitesh399** [LouisMazel/vue-phone-number-input#75]
## If I am using this input inside a form and going to select a country code then form submit event call because you did not define the type of button (Where to presenting the country code list). I think it is small issue but we can fixed it easily to add the type "button" 

![_t](https://user-images.githubusercontent.com/15153925/72138988-edccb580-33b3-11ea-8efc-285318ff10d9.png)

**Comment by LouisMazel** [comment]
It's already fixed in the latest version

[Commit](https://github.com/LouisMazel/vue-phone-number-input/commit/9ab18e157b4ef66ae3edc1a20d5a4e4067ff4706)

[Release](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.2)
