### ISSUE TITLE
(FEATURE REQUEST) Support for Typescript

### ISSUE THREAD

**Issue by albertpratomo** [LouisMazel/vue-phone-number-input#76]
## Is your feature request related to a problem? Please describe

Can't import the component in `main.ts`. Error:
```
Could not find a declaration file for module 'vue-phone-number-input'. Try `npm install @types/vue-phone-number-input` if it exists or add a new declaration (.d.ts) file containing `declare module 'vue-phone-number-input';`
```

## Describe the solution you'd like
Add declaration file and enable usage with Typescript.

**Comment by lesetse** [comment]
@albertpratomo  Did you try:

`Vue.component('vue-phone-number-input', VuePhoneNumberInput);
Vue.component('vue-otp-field', VueOTPField);`

**Comment by RacerDelux** [comment]
+1 for this.

**Comment by hathemi** [comment]
+1 for this !

**Comment by LouisMazel** [comment]
Hi @hathemi  @RacerDelux  @albertpratomo  @lesetse,

This plugin is unmaintained. Please use this one : 
- https://louismazel.github.io/maz-ui/documentation/maz-phone-number-input, and you have more features on it

And you have a simply typescript declaration to fix this error.

**How to use it ?** 

Follow this [getting started](https://louismazel.github.io/maz-ui/documentation/get-started)

Or, more simply : 

```bash
npm i maz-ui

# yarn add maz-ui
```

```vue 
<template>
  <MazPhoneNumberInput v-model="phoneNumber" />
</template>

<script lang="ts">
  import MazPhoneNumberInput from 'maz-ui/lib/maz-phone-number-input'
  import 'maz-ui/css/base.css'
  import 'maz-ui/css/maz-phone-number-input.css'
  
  export default {
    components: { MazPhoneNumberInput },
    data () {
      return {
        phoneNumber: undefined
      }
    }
  }
</script>

```

FYI: I have also the version for Vue 3 in beta : https://louismazel.github.io/maz-ui-3/components/maz-phone-number-input.html
With full typescript declaration file
Be careful, so many things can change in the futur
