### ISSUE TITLE
long country codes (4 numbers) return wrong prefix (BUG)

### ISSUE THREAD

**Issue by ancodeUDW** [LouisMazel/vue-phone-number-input#78]
## Describe the bug

If we pick a country with a long code (f.e. America Samoa = +1684) the component will return the country telephone code with only one number (+1)

## Steps to reproduce

Pick a country with long prefix (America Samoa, Antigua and Barbuda,  Bahamas, Barbados, Bermudas, Dominica...) and it will return always +1 instead of the real 4 number prefix

Example:

 1. Go to https://louismazel.github.io/vue-phone-number-input/ (component example)
 2. Click on Country code
 3. Scroll down to America Samoa (or any of the others with long Country code)
 4. See error: country code input shows +1, and in "Datas returned with "update" event" shows the wrong code in all the datas as well

## Expected behavior

Those countries codes must be the real ones (f.e. America Samoa = +1684)

## Device (please complete the following information)

- OS: Windows 10
- Browser: Chrome 79
- Package version: 1.1.3

## Additional context

-

**Comment by ancodeUDW** [comment]
In order to not to show the countries I tried to do a search and I added them to "ignored countries"

```
            :ignored-countries="['AS', 'AG', 'AI', 'BS', 'BB', 'BM', 'VG', 'GU', 'GD', 'JM',
            'MS', 'MP', 'KN', 'LC', 'VC', 'SX', 'VI', 'TC', 'TT', 'KY', 'DM']"
```

**Comment by aghafurqan87** [comment]
I am facing the same issue, is this fixed or still WIP? if not, is there any other way to make this work
