### ISSUE TITLE
Keyboard accessibility -> Searching country name in countries list

### ISSUE THREAD

**Issue by hitesh399** [LouisMazel/vue-phone-number-input#79]
Search By country name is not working properly.

## Steps to reproduce

Example:

 1. Click on country list selection to open the country list
 2. Start typing  like, India
 3. Then you got correct result
 4. Now the issue begin, Open the country list again.
 5. Start typing any letter but Now you did not get any result.

**Comment by LouisMazel** [comment]
I can't reproduce it... 

Have you more informations ?

**Comment by hitesh399** [comment]
When you click on "arrow down" button to open the country code list. the list is opening there is no problem but now you start to try any country name then result would not be filtered out based on typed keywords. 

@LouisMazel K It is only happened when you open the country code dropdown by clicking on arrow down button. 

If you are still not avail to reproduce it, I will send you git image.
