### ISSUE TITLE
Remove inline important styles

### ISSUE THREAD

**Issue by verstoff** [LouisMazel/vue-phone-number-input#8]
Inline styles (border 1px solid $color !important, etc) makes customization impossible with CSS.
It is worth adding the ability to disable focus styles like validation styles (no-validator-state).

**Comment by Daniel4Digital** [comment]
+1 here, I wanted to make it more material design with only border-bottom, but I had to manually edit the component code and removing the important from the borderStyle. It was a very simple removal.
It works without important perfectly, so there is no reason to have it on the component, and if anyone wants to customize the border, they'll be able. Win-Win situation for an easy fix.

**Comment by NicTorgersen** [comment]
It's possible to override with your own !important, but it's not optimal of course.

**Comment by ltroya-as** [comment]
@NicTorgersen I wasn't be able to override those values with my own important

**Comment by NicTorgersen** [comment]
@ltroya-as make sure your !important's are defined after the ones defined by this package.
