### ISSUE TITLE
Color props haven't access to loader color (BUG)

### ISSUE THREAD

**Issue by anywayscode** [LouisMazel/vue-phone-number-input#81]
## Color props haven't access to loader color

Trying to change loader color by writing `color="#e9932d"`, it's seems not working.

## Steps to reproduce

 1. Add prop `color="#000000"`
 2. Add prop `loader`
 3. See error

- Package version: [latest]

**Comment by LouisMazel** [comment]
Solved in 1.1.9

**RELEASE**: [https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.9](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.9)
