### ISSUE TITLE
`dark-color` prop has no effect (BUG)

### ISSUE THREAD

**Issue by paulbdavis** [LouisMazel/vue-phone-number-input#85]
## Describe the bug

I set `dark` and `dark-color="#1c1c1c"` on the component but nothing changes. I also tried setting it as `:dark-color="'#1c1c1c'"` with no luck.

## Steps to reproduce

As above

## Expected behavior

I would expect the dark setting to change the bg color to the one I specified, but it stays the same

## Screenshots

Not needed, it just looks like the default dark color all the time

## Device (please complete the following information)

- OS: Linux
- Browser: Firefox
- Package version: 1.1.5

**Comment by LouisMazel** [comment]
Solved in 1.1.6

[PR](https://github.com/LouisMazel/vue-phone-number-input/pull/87)
[Release](https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.6)
