### ISSUE TITLE
Make `box-shadow` CSS optional (FEATURE REQUEST)

### ISSUE THREAD

**Issue by paulbdavis** [LouisMazel/vue-phone-number-input#88]
## Is your feature request related to a problem? Please describe

I cannot seem to disable the box-shadow effect using my own CSS

## Describe the solution you'd like

Having an optional bool prop `no-box-shadow` or similar would be good to disable that.

## Describe alternatives you've considered

I tried to just add my own CSS to disable it seems the style on the component is scoped so I can't override it?

**Comment by Shade465** [comment]
I have the same problem

**Comment by LouisMazel** [comment]
Hi, 

Where you import the component, you use an unscoped css like this: 

```css
.input-tel__input {
  box-shadow: none !important;
}
```
