### ISSUE TITLE
[Feature Request] Set input maxlength based on example format

### ISSUE THREAD

**Issue by michieriffic** [LouisMazel/vue-phone-number-input#9]
Hi! I don't know if this feature would be good or not. 
Since we are able to show validation of format by changing the color of our input's border, maybe we can activate the max length of the input field based on the example format. 

This can be an option if other developers wants to limit it or not because maybe some countries might allow different type of phone number formats. I'm not sure.

Thanks :)

**Comment by Daniel4Digital** [comment]
A max-length would be very welcome!

**Comment by LouisMazel** [comment]
Will be not fixed, some countries have several possible lengths
