### ISSUE TITLE
(BUG) Hungary numbers validation is wrong

### ISSUE THREAD

**Issue by cageyv** [LouisMazel/vue-phone-number-input#91]
## Describe the bug

{ "countryCode": "HU", "isValid": true, "phoneNumber": "70123123", "countryCallingCode": "36", "formattedNumber": "+3670123123", "nationalNumber": "70123123", "formatInternational": "+36 70 123 123", "formatNational": "06 70 123 123", "uri": "tel:+3670123123", "e164": "+3670123123" }
+36 - country
70 - cellphone
123123 - number

6 digit number is incorrect. Need 7 digit. 
Like this: +36 1 234 5678 
+36 - country
1 - cellphone
234 5678 - number 

More info here: https://en.wikipedia.org/wiki/Telephone_numbers_in_Hungary

I checked the client base through the Google library and at the same time through the demo of this library vue found such an error.
Maybe someone will be useful

**Comment by LouisMazel** [comment]
Hi, 

This bug provide from [libphonenumber-js](https://github.com/catamphetamine/libphonenumber-js). You can report your bug on this library. 

I use it and there is nothing I can do.
The library validates the 6 and 7 digits
