### ISSUE TITLE
CSS Breaks in Nuxt production build when Tailwind is included

### ISSUE THREAD

**Issue by curtisburns** [LouisMazel/vue-phone-number-input#92]
## Describe the bug

The css breaks for the vue-phone-number-input component in production build for a 'create-nuxt-app ...' when configured to use @nuxtjs/tailwindcss. 

## Steps to reproduce

1. Run 'create-nuxt-app [name]'.
2. Select tailwind in the configuration.
3. npm install vue-phone-number-input.
4. Add the component to a page.
5. npm run build, then npm run dev. We can see the css is fine here.
6. npm run start. The css breaks.
7. Remove tailwind from the nuxt.config.js, and try npm run start again. Css is fixed.

## Expected behavior

Css should work alongside tailwind.

## Additional context

Apologies in advance, I'm not sure if this is an issue relating specifically to Nuxt, tailwind or vue-phone-number-input. This is more to put it on your radar.

**Comment by LouisMazel** [comment]
Hi, 

The bug it's already fixed on the new version of this component by prefix all css vars ! 
The new version of VuePhoneNumberInput is now on my **new library** [Maz-UI](https://louismazel.github.io/maz-ui/)

See **doc/demo** page of [MazPhoneNumberInput](https://louismazel.github.io/maz-ui/#/documentation/phone-number-input)
Some options may change, check the props documentation with the top right button

In this new library, you can enjoy lot of others components in the same style. 
You can just install the component you want (and not the whole library), for this
Read the [Get started](https://louismazel.github.io/maz-ui/#/documentation/get-started) page

If you have any problem or question, do no hesitate to ask me !
