### ISSUE TITLE
Can't get Country Code to work programmatically (question)

### ISSUE THREAD

**Issue by mberkeland** [LouisMazel/vue-phone-number-input#93]
I need to set the phone number WITH country code programmatically. I set the default country code to a variable, but changing that variable does nothing. I am using v1.1.6.  I have tried the trick in https://github.com/LouisMazel/vue-phone-number-input/issues/30 , and that almost works.. I can get the country code to change, but I can't get the phone number to stay.  I have tried every combination I can think of using the onUpdate and $ref tricks, but cannot get the number and country code to update.  I suspect I am missing something simple, but I haven't hit upon it yet.  Is there a way to do this?

**Comment by LouisMazel** [comment]
Solved in 1.1.7

Release : https://github.com/LouisMazel/vue-phone-number-input/releases/tag/1.1.7
