### ISSUE TITLE
Invalid prop: type check failed for prop "translations"

### ISSUE THREAD

**Issue by offshorewahoo** [LouisMazel/vue-phone-number-input#96]
I'm trying to use features such as setting translations, so that I can hide the placeholder completely.

This is what I have for my template:

    <vue-phone-number-input v-model="yourValue" default-country-code="US" no-country-selector="true" translations="{ phoneNumberLabel: 'hello' }" />

I am getting warnings like this:

[Vue warn]: Invalid prop: type check failed for prop "translations". Expected Object, got String with value "{ phoneNumberLabel: 'hello' }".

found in

---> <MazPhoneNumberInput>
       <Test> at src/views/Test.vue
         <App> at src/App.vue
           <Root>

**Comment by LouisMazel** [comment]
The good syntax:

```html
<vue-phone-number-input v-model="yourValue" default-country-code="US" no-country-selector="true" :translations="{ phoneNumberLabel: 'hello' }" />
```

**Comment by offshorewahoo** [comment]
Got it! Thank you!

AN
