### ISSUE TITLE
Country selec dropdown not adjusting height

### ISSUE THREAD

**Issue by elC0mpa** [LouisMazel/vue-phone-number-input#99]
## Describe the bug
If you use the only-countries property and select, for example, two countries, the dropdown element will display some blank items which shouldn't be shown as you can see below:

## Steps to reproduce
Make sure that the component works with less than five countries and try to choose one, you will see a lot of blank items in the dropdown element

## Expected behavior
The dropdown height must be the necessary for displaying the countries used

## Screenshots
![image](https://user-images.githubusercontent.com/53531665/83321992-2b769180-a222-11ea-8317-30293e645350.png)

## Device

- OS: Windows 10
- Browser: Chrome 83.0
- Package version: e.g. 1.1.9

**Comment by LouisMazel** [comment]
Hi,

The bug it's already fixed on the new version of this component !
The new version of VuePhoneNumberInput is now on my new library Maz-UI

See doc/demo page of MazPhoneNumberInput
Some options may change, check the props documentation with the top right button

In this new library, you can enjoy lot of others components in the same style.
You can just install the component you want (and not the whole library), for this
Read the Get started page

If you have any problem or question, do no hesitate to ask me !
